In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
## Define the vocabulary size
voc_size=10000

In [5]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [6]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[5486, 9295, 5278, 6019],
 [5486, 9295, 5278, 392],
 [5486, 4924, 5278, 3274],
 [6362, 2405, 5196, 4647, 1689],
 [6362, 2405, 5196, 4647, 1310],
 [6001, 5486, 8791, 5278, 8336],
 [3610, 5459, 9151, 4647]]

In [7]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [8]:
import numpy as np

In [9]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 5486 9295 5278 6019]
 [   0    0    0    0 5486 9295 5278  392]
 [   0    0    0    0 5486 4924 5278 3274]
 [   0    0    0 6362 2405 5196 4647 1689]
 [   0    0    0 6362 2405 5196 4647 1310]
 [   0    0    0 6001 5486 8791 5278 8336]
 [   0    0    0    0 3610 5459 9151 4647]]


In [10]:
## feature representation
dim=10

In [11]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [12]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [13]:
model.predict(embedded_docs)


1/1 [==============================] - 0s 183ms/step


array([[[ 0.04501705, -0.01340604, -0.04285672, -0.02330656,
         -0.01740896,  0.01240792, -0.03248087,  0.01256293,
         -0.03580751, -0.03253174],
        [ 0.04501705, -0.01340604, -0.04285672, -0.02330656,
         -0.01740896,  0.01240792, -0.03248087,  0.01256293,
         -0.03580751, -0.03253174],
        [ 0.04501705, -0.01340604, -0.04285672, -0.02330656,
         -0.01740896,  0.01240792, -0.03248087,  0.01256293,
         -0.03580751, -0.03253174],
        [ 0.04501705, -0.01340604, -0.04285672, -0.02330656,
         -0.01740896,  0.01240792, -0.03248087,  0.01256293,
         -0.03580751, -0.03253174],
        [-0.03608223, -0.03641721,  0.00314583, -0.04648194,
          0.01124761, -0.04463581,  0.01744547,  0.0026224 ,
          0.04800166,  0.02188062],
        [-0.00155023,  0.04596357, -0.03896364,  0.0221099 ,
          0.04313118,  0.04825315,  0.0174864 ,  0.01628968,
          0.02147106, -0.0344707 ],
        [ 0.03001828, -0.03940222, -0.01039921,  0.0

In [14]:
embedded_docs[0]

array([   0,    0,    0,    0, 5486, 9295, 5278, 6019])

In [16]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 94ms/step


array([[ 0.04501705, -0.01340604, -0.04285672, -0.02330656, -0.01740896,
         0.01240792, -0.03248087,  0.01256293, -0.03580751, -0.03253174],
       [ 0.04501705, -0.01340604, -0.04285672, -0.02330656, -0.01740896,
         0.01240792, -0.03248087,  0.01256293, -0.03580751, -0.03253174],
       [ 0.04501705, -0.01340604, -0.04285672, -0.02330656, -0.01740896,
         0.01240792, -0.03248087,  0.01256293, -0.03580751, -0.03253174],
       [ 0.04501705, -0.01340604, -0.04285672, -0.02330656, -0.01740896,
         0.01240792, -0.03248087,  0.01256293, -0.03580751, -0.03253174],
       [-0.03608223, -0.03641721,  0.00314583, -0.04648194,  0.01124761,
        -0.04463581,  0.01744547,  0.0026224 ,  0.04800166,  0.02188062],
       [-0.00155023,  0.04596357, -0.03896364,  0.0221099 ,  0.04313118,
         0.04825315,  0.0174864 ,  0.01628968,  0.02147106, -0.0344707 ],
       [ 0.03001828, -0.03940222, -0.01039921,  0.03783511,  0.01265606,
        -0.04846878, -0.00614376, -0.02371366